name: essential
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  blurhash_dart: ^1.2.1
  cached_network_image: ^3.3.1
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  formz: ^0.7.0
  gap: ^3.0.1
  google_sign_in: ^6.2.1
  http: ^1.2.1
  image: ^4.1.7
  image_picker: ^1.1.0
  supabase_flutter: ^2.5.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/